#!/usr/bin/env bash
# customising a 404 page

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.blog.rarimuk.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

#creating a 404 erro page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

string_for replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var/www/html;\n\t\internal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$string_for_replacemt/" /etc/nginx/sites-enabled/default

#restart nginx after implementing changes

sudo service nginx restart
